@startuml

actor "Administrator" as P #DAE8FC
participant ":Main UI" as M #DAE8FC
participant ":ImportReadingsFromFileUI" as U #DAE8FC
participant ":ImportReadingsFromFileController" as C #DAE8FC
participant ":ListOfGeographicArea" as LG #DAE8FC
participant "reader:JsonReader" as COX #DAE8FC

skinparam actor {
	BorderColor 6C8EBF
}

skinparam participant {
	BorderColor 6C8EBF
}

skinparam shadowing false

skinparam sequence {
	ArrowColor BLACK
	ActorBorderColor DeepSkyBlue
	LifeLineBorderColor BLACK
}
U -> P: Request file path
P-->U: file path
U->C:addReadingsToSensors(reader,path)
activate C
C->COX:importReadingsOfSensor(path)
activate COX
COX-->C:listOfReadingsDto
deactivate COX
C -> LG: getAllSensors( )
activate LG
LG --> C: listOfAreaSensors
deactivate LG
C -> C: setReadingsBySensorIDescription( )
C --> U: number of lines added
deactivate C
U --> P: number of lines added

@enduml