@startuml

GeographicArea -> GeographicAreaType: setmGeographicAreaType
GeographicAreaType -> ListOfGeographicArea: getmListOfGArea
ListOfGeographicArea --> GeographicArea: geographicAreaIsInsideOfOtherGeographicArea

@enduml