@startuml

skinparam Component {
    BackgroundColor #DAE8FC
	ArrowColor Black
	BorderColor 6C8EBF
	FontSize 15
	FontColor Black
	style Frame
	FontStyle bold
	FontName Arial Rounded MT Bold
}

skinparam componentAttributeFontSize 13

skinparam shadowing false

skinparam defaultFontName Segoe UI


package "Architecture Diagram" {
       [UI] --0)- [Controller]
       [Model] --up(0- [Controller]
       [Controller] --right(0--[Mapper]
       [Mapper] --(0- [Dto]
       [Repository] --up(0- [Model]
       }
       @enduml