@startuml

skinparam class {
    HeaderBackgroundColor #DAE8FC
	BackgroundColor White
	ArrowColor black
	BorderColor 6C8EBF
	FontSize 15
	headerFontColor 6C8EBF
	style Frame
	FontName Arial Rounded MT Bold

	}
hide circle

skinparam classAttributeIconSize 0

skinparam classAttributeFontSize 13

skinparam shadowing false

skinparam defaultFontName Segoe UI
class AttachDetachRoomToHouseGridRestController
class HouseGridRepo
class RoomRepo
class RoomHouseGridService
class MapperListOfHouseGrid


AttachDetachRoomToHouseGridRestController "1" --> "1" RoomHouseGridService
RoomHouseGridService "1" --> "1" HouseGridRepo
RoomHouseGridService "1" --> "1" RoomRepo
HouseGridRepo "1" --> "1" MapperListOfHouseGrid

AttachDetachRoomToHouseGridRestController : + getListOfHouseGrids ( )
AttachDetachRoomToHouseGridRestController : + getListOfRoomsAttachedToHouseGrid ( )
AttachDetachRoomToHouseGridRestController : + detachRoomFromHouseGrid ( )

MapperListOfHouseGrid : + toDto

RoomRepo : + getRoomByName ( )

HouseGridRepo : + getHouseGridByCode ( )

RoomHouseGridService : + removeRoomFromHouseGridIds ( )
RoomHouseGridService : + removeRoomFromHouseGrid ( )

@enduml